version: "3"

services:

  nginx:
    image: "nginx:latest"
    restart: "always"
    container_name: "docs"
    volumes:
      - ../../:/usr/share/nginx/html/docs
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "1234:80"

